version: '3'

services:
  containerized-cyclegan:
    image: valerianomanassero/containerized-cyclegan:latest
    environment:
      - OPTIONS_MODE=0
      - OPTIONS_EPOCH=0
      - OPTIONS_N_EPOCHS=200
      - OPTIONS_BATCHSIZE=1
      - OPTIONS_MODE=/dataset/
      - OPTIONS_LEARNING_RATE=0.0002
      - OPTIONS_DECAY_EPOCH=100
      - OPTIONS_CROP_SIZE=256
      - OPTIONS_INPUT_NC=3
      - OPTIONS_OUTPUT_NC=3
      - OPTIONS_MODE=True
      - OPTIONS_N_CPU=8
    volumes:
      - ./app:/app
      - ./dataset:/dataset
      - ./output:/output